server:
  port: 7070
  tomcat:
    threads:
      max: 100
    accept-count: 100

spring:
  datasource:
    hikari:
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 0
      minimum-idle: 10
      maximum-pool-size: 10
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/haohao_admin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/haohao_admin_slave?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: root

  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password: root
    lettuce:
      pool:
        max-active: 100
        max-idle: 50
        max-wait: 500
        min-idle: 0

knife4j:
  enable: true
  setting:
    enable-debug: false
    enable-search: false
  openapi:
    title: haohao-admin api doc
    version: v1.0
    group:
      system:
        group-name: 系统模块
        api-rule: package
        api-rule-resources:
          - com.haohao.admin.module.system.controller
      test:
        group-name: 测试模块
        api-rule: package
        api-rule-resources:
          - com.haohao.admin.module.test.controller
      exam:
        group-name: 考试模块
        api-rule: package
        api-rule-resources:
          - com.haohao.admin.module.exam.controller
      auth:
        group-name: 权限模块
        api-rule: package
        api-rule-resources:
          - com.haohao.admin.auth.controller
logging:
  config: classpath:log/logback-dev.xml